Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "./sync", "/vagrant/data"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  # end
  
  config.vm.provision "shell", inline: <<-SHELL
     yumt update
     yum install -y vim
     yum install -y git
     yum install -y docker
     curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
     chmod +x /usr/local/bin/docker-compose
   SHELL
   
end
